name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  prepare_image:
    runs-on: ubuntu-latest
    environment: docker-env
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nhatbangle/demo-btpm:latest
    - name: Log in to Docker
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u nhatbangle --password-stdin
    - name: Push the Docker image
      run: docker push nhatbangle/demo-btpm:latest
